/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans._14;

import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author kim
 */
public class MenuActionEventEx extends javax.swing.JFrame {

//    public Container contentPane;
    public JLabel imgLabel = new JLabel(); // 빈 이미지를 가진 레이블
    
    private void createMenu(){
        
        JMenuBar mb = new JMenuBar(); // 메뉴바 생성
        JMenuItem [] menuItem = new JMenuItem [4];
        String[] itemTitle = {"Load", "Hide", "ReShow", "Exit"};
        JMenu screenMenu = new JMenu("Screen");

        // 4개의 메뉴아이템을 Screen 메뉴에 삽입한다.
        MenuActionListener listener = new MenuActionListener(); // Action 리스너 생성
        for(int i=0; i<menuItem.length; i++) {
                menuItem[i] = new JMenuItem(itemTitle[i]); // 메뉴아이템 생성
                menuItem[i].addActionListener(listener); // 메뉴아이템에 Action 리스너 등록
                screenMenu.add(menuItem[i]); // 메뉴아이템을 Screen 메뉴에 삽입
        }
        mb.add(screenMenu); // 메뉴바에 Screen 메뉴 삽입
        setJMenuBar(mb); // 메뉴바를 프레임에 부착
        
        
    }// createMenu()
    
    
    class MenuActionListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            String cmd = e.getActionCommand(); // 사용자가 선택한 메뉴아이템의 문자열 리턴
            switch(cmd) { // 메뉴 아이템의 종류 구분
                case "Load" : 
                    if(imgLabel.getIcon() != null)
                        return; // 이미 로딩되었으면 리턴
                    imgLabel.setIcon(new javax.swing.ImageIcon("images/img.jpg"));
                    break;
                case "Hide" :		
                    imgLabel.setVisible(false); 
                    break;
                case "ReShow" : 
                    imgLabel.setVisible(true); 
                    break;
                case "Exit" : 
                    System.exit(0); 
                    break;
            }
        }
        
    }// class MenuActionListener
    
    
    
    
    
    
    /**
     * Creates new form MenuActionEventEx
     * 이미지 로딩이 않된다.. 이유를 모르겠음
     */
    public MenuActionEventEx() {
        getContentPane().add(imgLabel, BorderLayout.CENTER);
        createMenu();
        setSize(250, 220);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu에 Action 리스너 만들기 예제");
        setPreferredSize(null);
        setSize(new java.awt.Dimension(250, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuActionEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuActionEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuActionEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuActionEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuActionEventEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
