/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _help4;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author admin
 */
public class MemoGUI extends javax.swing.JFrame {

    /**
     * Creates new form MemoGUI
     */
    private MemoDAO dao;
    public MemoGUI() {
        initComponents();
        dao=new MemoDAO();
        //윈도우 이벤트 처리
        addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
                dao.dbClose();
                System.exit(0);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tp = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbIdx = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        lbWdate = new javax.swing.JLabel();
        tfMsg = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();
        btList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btUpdateOK = new javax.swing.JButton();
        lbIdx2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taList = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        comboType = new javax.swing.JComboBox<>();
        tfFind = new javax.swing.JTextField();
        btFind = new javax.swing.JButton();
        btAll = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::: 한줄 메모장 v1.1:::");
        setIconImage(Toolkit.getDefaultToolkit().getImage("../star.PNG"));

        jLabel1.setFont(new java.awt.Font("나눔고딕", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("::::한줄 메모장:::");

        lbIdx.setBackground(new java.awt.Color(204, 255, 204));
        lbIdx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tfName.setBorder(javax.swing.BorderFactory.createTitledBorder("작성자"));

        lbWdate.setFont(new java.awt.Font("나눔고딕", 1, 14)); // NOI18N
        lbWdate.setForeground(new java.awt.Color(153, 0, 153));
        lbWdate.setText("2016년 00월 00일");

        tfMsg.setBorder(javax.swing.BorderFactory.createTitledBorder("메모 내용"));

        btInsert.setBackground(new java.awt.Color(0, 102, 102));
        btInsert.setForeground(new java.awt.Color(255, 255, 255));
        btInsert.setMnemonic('I');
        btInsert.setText("글쓰기");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        btList.setBackground(new java.awt.Color(255, 204, 204));
        btList.setForeground(new java.awt.Color(153, 0, 0));
        btList.setMnemonic('L');
        btList.setText("글목록");
        btList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/memo_jdbc/star.PNG"))); // NOI18N

        btDelete.setBackground(new java.awt.Color(255, 255, 153));
        btDelete.setForeground(new java.awt.Color(0, 0, 255));
        btDelete.setMnemonic('D');
        btDelete.setText("글삭제");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btUpdate.setBackground(new java.awt.Color(255, 204, 204));
        btUpdate.setMnemonic('U');
        btUpdate.setText("글수정");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btUpdateOK.setBackground(new java.awt.Color(255, 51, 255));
        btUpdateOK.setMnemonic('O');
        btUpdateOK.setText("수정처리");
        btUpdateOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateOKActionPerformed(evt);
            }
        });

        lbIdx2.setText("^^");

        javax.swing.GroupLayout lbIdxLayout = new javax.swing.GroupLayout(lbIdx);
        lbIdx.setLayout(lbIdxLayout);
        lbIdxLayout.setHorizontalGroup(
            lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbIdxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbIdxLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUpdateOK)
                        .addGap(18, 18, 18))
                    .addGroup(lbIdxLayout.createSequentialGroup()
                        .addGroup(lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbIdxLayout.createSequentialGroup()
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbIdx2)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbWdate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 98, Short.MAX_VALUE))
                            .addComponent(tfMsg))
                        .addContainerGap())))
        );
        lbIdxLayout.setVerticalGroup(
            lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbIdxLayout.createSequentialGroup()
                .addGroup(lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbIdxLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbWdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lbIdxLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(lbIdxLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbIdx2)))
                .addGap(18, 18, 18)
                .addComponent(tfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lbIdxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsert)
                    .addComponent(btList)
                    .addComponent(btDelete)
                    .addComponent(btUpdate)
                    .addComponent(btUpdateOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taList.setEditable(false);
        taList.setColumns(20);
        taList.setRows(5);
        taList.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 3, true));
        jScrollPane1.setViewportView(taList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lbIdx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIdx, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tp.addTab("메모등록", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "작성자", "메모내용", "글번호" }));

        tfFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFindActionPerformed(evt);
            }
        });

        btFind.setText("글검색");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        btAll.setText("전체글");
        btAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAll)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAll, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfFind, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btFind, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "글번호", "작성자", "메모내용", "작성일"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 646, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        tp.addTab("메모 검색", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUpdateOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateOKActionPerformed
        //1. 수정할 값 받아오기 (작성자, 메모내용, 글번호)
        String idxStr=lbIdx2.getText();
        String name=tfName.getText();
        String msg=tfMsg.getText();

        //2. MemoDTO객체에 수정할 값 담아주기
        try{
            int idx=Integer.parseInt(idxStr);
            MemoDTO memo=new MemoDTO(idx,name,msg, null);
            //3. dao의 updateMemo(memo) 호출
            boolean bool=dao.updateMemo(memo);
            String str=(bool)?"수정 성공":"수정 실패";
            //4. 수정 결과 메시지 처리
            showMsg(str);
        }catch(NumberFormatException e){
            showMsg("글 수정 버튼을 먼저 누르세요");
        }
    }//GEN-LAST:event_btUpdateOKActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        //1. 수정할 글 번호를 입력받는다.
        String strIdx=JOptionPane.showInputDialog("수정할 글번호를 입력하세요");
        if(strIdx==null) return;
        //2. 해당 글 내용을 dao에서 받아온다.
        MemoDTO m=dao.selectMemoByIdx(Integer.parseInt(strIdx.trim()));

        //3. tfName, tfMsg에 해당 내용을 보여준다.
        if(m!=null){
            lbIdx2.setText(m.getIdx()+"");
            tfName.setText(m.getName());//작성자
            tfMsg.setText(m.getMsg());//메모내용
            lbWdate.setText(m.getWdate().toString());//작성일
        }else{
            showMsg(strIdx+"번 글은 존재하지 않아요!");
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        //1. 삭제할 글 번호를 입력받는다.
        String strIdx=JOptionPane.showInputDialog("삭제할 글 번호를 입력하세요");
        if(strIdx==null) return;
        //2. dao의 삭제 처리 메소드 호출
        boolean bool=dao.deleteMemo(Integer.parseInt(strIdx.trim()));

        //3. 실행 결과 메시지 처리
        String str=(bool)?"삭제 성공":"삭제 실패";
        showMsg(str);
        all();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListActionPerformed
        all();
    }//GEN-LAST:event_btListActionPerformed

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        String name=tfName.getText();
        String msg=tfMsg.getText();
        if(name==null || name.trim().equals("")){
            JOptionPane.showMessageDialog(this, "작성자를 입력하세요");
            tfName.requestFocus();
            return;
        }
        if(msg==null|| msg.length()>100){
            JOptionPane.showMessageDialog(this, "메모내용은 0~100자 이내여야 해요");
            tfMsg.requestFocus();
            return;
        }
        MemoDTO memo=new MemoDTO();
        memo.setName(name);
        memo.setMsg(msg);

        boolean bool=dao.insertMemo2(memo);
        String str=bool ? "등록 성공":"등록 실패";
        showMsg(str);
        clearTf();
        all();//게시글 가져오기
    }//GEN-LAST:event_btInsertActionPerformed

    private void tfFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFindActionPerformed
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_tfFindActionPerformed

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_btFindActionPerformed

    private void btAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAllActionPerformed
        allTable();
    }//GEN-LAST:event_btAllActionPerformed

    public void allTable(){
        Vector<MemoDTO> allV=dao.selectAllMemo();
        showTable(allV);
    }
    
    
    public void find(){
       // 1. 검색 유형값 얻어오기 => comboType으로 부터
         int index=comboType.getSelectedIndex();
         //작성자 => 0   메시지=>1   글번호=>2
         if(index<0) return;
                
        //2. 검색어 얻어오기
        String keyword=this.tfFind.getText();
        if(keyword==null || keyword.trim().equals("")){
            showMsg("검색어를 입력하세요");
            tfFind.requestFocus();
            return;
        }
        
       // 3. dao의 findMemo(검색유형, 검색어) 호출       
       Vector<MemoDTO>  mv=dao.findMemo(index, keyword);
                
        //4. 결과값 받아서 table에 출력
        if(mv!=null){
            showTable(mv);
        }
    }//----------------------------------------
    
//    벡터의 내용을 꺼내와 jtable에 보여주는 메소드
    private void showTable(Vector<MemoDTO> mv) {
        //데이터=> 모델 DefaultTableModel
        Object[][]data=new Object[mv.size()][4];
        for(int i=0;i<data.length; i++){
            MemoDTO m=mv.get(i);
            data[i][0]=m.getIdx();
            data[i][1]=m.getName();
            data[i][2]=m.getMsg();
            data[i][3]=m.getWdate();
        }//for----------
        String[] colNames={"글번호","작성자","메모내용","작성일"};
        DefaultTableModel model=new DefaultTableModel(data, colNames);
        //View와 Model을 연결
        table.setModel(model);
        
    }//----------------------------------------
    
    public void clearTf(){
        tfName.setText("");
        tfMsg.setText("");
        tfName.requestFocus();
    }
    
    
    public void showMsg(String msg){
        JOptionPane.showMessageDialog(this, msg);
    }
    
    
    public void all(){
        Vector<MemoDTO> allV=dao.selectAllMemo();
        if(allV !=null){
            taList.setText(allV.size()+"개의 글이 있어요");
            String str="";
            for(MemoDTO m:allV){
         str+=m.getIdx()+"\t"+m.getName()+"\t"+m.getMsg()+"\t"+m.getWdate()+"\r\n";
            }
            taList.setText(str);
        }
    }    //m50-573-072
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAll;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btList;
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btUpdateOK;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lbIdx;
    private javax.swing.JLabel lbIdx2;
    private javax.swing.JLabel lbWdate;
    private javax.swing.JTextArea taList;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfFind;
    private javax.swing.JTextField tfMsg;
    private javax.swing.JTextField tfName;
    private javax.swing.JTabbedPane tp;
    // End of variables declaration//GEN-END:variables

    
}
