import java.awt.Color;
import java.awt.event.*;
import java.sql.*;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author kodica07
 */
public class MySQLPlusGui extends javax.swing.JFrame {

    /**
     * Creates new form MySQLPlusGui
     */
	Connection con;
	Statement st;
	ResultSet rs;
    public MySQLPlusGui() {
        initComponents();
        tfHost.setText("127.0.0.1");
        tfUser.setText("Scott");
        tfPwd.setText("tiger");
        
        addWindowListener( new WindowListener(){
			public void WindowClosing(WindowEvent e){
        		DbUtil.close(rs, st, con);
        	}

			@Override
			public void windowActivated(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void windowClosed(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void windowClosing(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void windowDeactivated(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void windowDeiconified(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void windowIconified(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void windowOpened(WindowEvent e) {
				// TODO Auto-generated method stub
				
			}
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfHost = new javax.swing.JTextField();
        tfUser = new javax.swing.JTextField();
        tfPwd = new javax.swing.JPasswordField();
        btCon = new javax.swing.JButton();
        lbResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfSql = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::: MysqlPlusGui:::");

        tfHost.setBorder(javax.swing.BorderFactory.createTitledBorder("호스트"));

        tfUser.setBorder(javax.swing.BorderFactory.createTitledBorder("사용자"));

        tfPwd.setBorder(javax.swing.BorderFactory.createTitledBorder("비밀번호"));

        btCon.setText("DB연결");
        btCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConActionPerformed(evt);
            }
        });

        lbResult.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\java\\_lecture\\study\\test_school\\Advance\\pic.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        tfSql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSql, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfHost, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCon))
                            .addComponent(lbResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfPwd, tfUser});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tfSql, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCon, tfHost, tfPwd, tfUser});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void btConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConActionPerformed
        // 호스트, 유저 ,pwd받기
    	// 192.168.10.150 -> 강사피시
    	// 192.168.10.98 -> 내아피이
    	// 192.168.10.23 -> 옆친구
    	String host = tfHost.getText();
    	if(host==null || host.trim().isEmpty()){
    		host = "localhost";
    	}
    	String user = tfUser.getText();
    	char ch[] = tfPwd.getPassword();
    	String pwd = new String(ch, 0, ch.length);

    	String strUrl = "jdbc:oracle:thin:@" + host + ":1521:ORCL";
    	
    	DbUtil.setUrl(strUrl);
    	//DbUtil.setHost(host);
    	DbUtil.setUser(user);
    	DbUtil.setPwd(pwd);
    	
    	try {
    		con=DbUtil.getCon();
    		lbResult.setText(tfHost.getText() + "DB연결 성공");;
    	} catch(Exception e){
    		lbResult.setText(tfHost.getText() + "DB연결 오류");
    	}
    	
    }//GEN-LAST:event_btConActionPerformed

    private void tfSqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSqlActionPerformed
        // 
    	execute();
    	
    }//GEN-LAST:event_tfSqlActionPerformed
 
    
    
    // sql execute() 메서드는 모든 문장을 실행가능한 장점이 있다.
    private void execute() {

    	String sql = tfSql.getText();		// tfSql에 입력받은 sql 문을 얻어온다.
    	int index = sql.indexOf(";");    	// ; 이 있는 지 검색하고 있으면 ;을 제외한 sql문을 완성. // ; 찾아서 위치를 반환
    	
    	if(index != -1) {
    		sql = sql.substring(0, index);	// 0에서 ;찾은 위치까지 반환
    	}
    	
    	if(sql.trim().isEmpty()) {
    		return;
    	}
    	
    	
    	
    	try {
        	// st를 얻어 ,  select, insert, update
        	st = con.createStatement();
        	
        	// sql문을 실행시킨다. => boolean execute(String sql);
        	boolean bool = st.execute(sql);
        	
        	if( bool ) { 	// select 문장
        		rs = st.getResultSet();
        		printResultSet(rs);
        		
        	} else { 		// select가 아닌 문장
            	// 결과값을 lbResult에 출력해보기
        		// SQL문에 의해 영향받은 레코드 수를 출력
        		int cnt = st.getUpdateCount();
    			lbResult.setText("결과 : " + cnt + "개의 레코드가 변경되었습니다.");
    			lbResult.setForeground(Color.blue);
        	}
    		
        	if( st!=null) st.close();
		} catch (SQLException e) {
			lbResult.setText(e.getMessage());
			lbResult.setForeground(Color.red);
		}// try
    	
	}// execute;
    
    
	private void printResultSet(ResultSet rs2) 
	throws SQLException
	{
		

		
		
		
		// 4. 반복문 돌면서 컬럼명을 알아내어 배열에 저장
		// 4_2. rs의 컬럼데이터를 꺼내와 배열에 저장
		
		// 5. DefaultTableModel을 생성하여 컬럼 제목을 넣어보자.
		
		// 6. table과 Model을 연결

		
		
		// 1. 컬럼정보를 얻기 위해 ResultSetMetaData를 얻어온다.
		ResultSetMetaData rsmd = rs.getMetaData();
		// 2. rsmd를 통해 컬럼수를 알아낸다.
		int colCount = rsmd.getColumnCount();
		// 3. 컬럼명을 담아줄 1차원 배열을 생성
		String[] colNames = new String[colCount];
		// 4. 반복문 돌면서 컬럼명을 알아내어 배열에 저장
		for(int i=0; i<colCount; i++){
			colNames[i]=rsmd.getColumnName(i+1);// 배열에 컬럼 할당
		}
		
		DefaultTableModel model = new DefaultTableModel();// 모델초기화
		model.setColumnIdentifiers(colNames);/// 컬럼초기화
		
/*		for(int i=0; rs.next(); i++)
		{
			System.out.println(rs.getRow());
		}*/
		
		String[] data = new String[colCount];;// 데이터를 담을 배열
		
		while(rs.next()){
			
			for(int i=0; i<colCount; i++){
				String colData = rs.getString(i+1);	// 오라클은 1부터 시작
				data[i] = colData;						// 한행 가져와서 data[i]에 저장
			}
			model.addRow(data);						// 레코드 추가
		}
		
		jTable1.setModel(model);// JTable에 모델세팅
		
		
		
/*
# listener.ora Network Configuration File: C:\app\kodica07\product\12.1.0\dbhome_1\network\admin\listener.ora
# Generated by Oracle configuration tools.

SID_LIST_LISTENER =
  (SID_LIST =
    (SID_DESC =
      (SID_NAME = CLRExtProc)
      (ORACLE_HOME = C:\app\kodica07\product\12.1.0\dbhome_1)
      (PROGRAM = extproc)
      (ENVS = "EXTPROC_DLLS=ONLY:C:\app\kodica07\product\12.1.0\dbhome_1\bin\oraclr12.dll")
    )
  )

LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.10.98)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )




# tnsnames.ora Network Configuration File: C:\app\kodica07\product\12.1.0\dbhome_1\network\admin\tnsnames.ora
# Generated by Oracle configuration tools.

LISTENER_ORCL =
  (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.10.98)(PORT = 1521))


ORACLR_CONNECTION_DATA =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
    (CONNECT_DATA =
      (SID = CLRExtProc)
      (PRESENTATION = RO)
    )
  )

ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.10.98)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )



*
*/
		
		
	} // private void printResultSet(ResultSet rs2)
    //////////////////////////////////////////////////////////////////
    // test
	// Insert into emp2 Values();
    // delete emp2;
    // drop emp2;
    // create table emp2 as select * from emp where deptno=10;
    //////////////////////////////////////////////////////////////////



	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MySQLPlusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MySQLPlusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MySQLPlusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MySQLPlusGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MySQLPlusGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbResult;
    private javax.swing.JTextField tfHost;
    private javax.swing.JPasswordField tfPwd;
    private javax.swing.JTextField tfSql;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
