/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import java.awt.Container;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author kim
 */
public class CheckBoxItemEventEx extends javax.swing.JFrame {

    private JCheckBox fruits[] = new JCheckBox[3];  // 체크박스 배열
    private String names[] = {"사과", "배", "체리" };// 체크박스 문자열로 사용할 문자열 배열
    private JLabel sumLabel;                        // 계산 합을 출력할 레이블
    
    /**
     * Creates new form CheckBoxItemEventEx
     */
    public CheckBoxItemEventEx() {
        initComponents();
        
        Container c = getContentPane();
        
        // MyItemListener 생성
        MyItemListener listener = new MyItemListener();
        
        // 3개의 체크박스를 생성, 컨텐트 팬에 삽입하고 Item리스너 등록
        // 배열로 박스있는 레이블 3개 만들기
        for(int i=0; i<fruits.length; i++) {
            fruits[i] = new JCheckBox(names[i]);// 문자열로 체크박스 생성
            fruits[i].setBorderPainted(true);   // 체크박스 외곽선 보이도록 설정
            c.add(fruits[i]);                   // 컨텐트 팬 추가
            fruits[i].addItemListener(listener);// fruits배열마다 JCheckBox에 addItemListener에 리스너 등록
        }// for
        
        // 가격합을 출력하는 레이블 생성
        sumLabel = new JLabel("현재 0원 입니다.");
        c.add(sumLabel);
        
        
    }// CheckBoxItemEventEx()

    
    class MyItemListener implements ItemListener
    {
        private int sum = 0; // 가격의 합
        @Override
        public void itemStateChanged(ItemEvent e) {
            if(e.getStateChange() == ItemEvent.SELECTED) {
                
                if(e.getItem() == fruits[0]){
                    sum += 100;// 사과 합
                } else if(e.getItem() == fruits[1]){
                    sum += 500;// 배 합
                } else {
                    sum += 20000;// 체리 합
                }
                
            } else {
                if(e.getItem() == fruits[0]){
                    sum -= 100;// 사과 합
                } else if(e.getItem() == fruits[1]){
                    sum -= 500;// 배 합
                } else {
                    sum -= 20000;// 체리 합
                }
            }// if
            
            sumLabel.setText("현재 " + sum + "원 입니다.");
        }// itemStateChanged()
        
    }// class MyItemListener
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("체크박스와 ItemEvent 예제");
        setMinimumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(250, 250));
        setSize(new java.awt.Dimension(250, 250));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("사과 100원, 배 500원, 체리 20,000원");
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBoxItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBoxItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBoxItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBoxItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBoxItemEventEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
