/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author user
 */
public class ComboActionEx extends javax.swing.JFrame {

    
    // 콤보박스의 아이템
    private String fruits[] = {"apple", "banana", "kiwi","mango"};
    
    // 이미지 객체 배열
    private ImageIcon images[] = {
        new ImageIcon("images/apple2.jpg"),
        new ImageIcon("images/banana2.jpg"),
        new ImageIcon("images/kiwi2.jpg"),
        new ImageIcon("images/mango2.jpg")
    };
    
    
    
    
    /**
     * Creates new form ComboActionEx
     */
    public ComboActionEx() {
        initComponents();
        
//        // 이미지 레이블 컴포넌트
//        imgLabel = new JLabel(images[0]);
//
//        // 문자열 콤보박스 컴포넌트
//       strCombo = new JComboBox<String>(fruits);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLabel = new javax.swing.JLabel(images[0]);
        strCombo = new javax.swing.JComboBox<String>(fruits);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("콤보박스 활용 예제");
        setMinimumSize(new java.awt.Dimension(300, 250));
        setPreferredSize(new java.awt.Dimension(300, 250));
        setSize(new java.awt.Dimension(300, 250));
        getContentPane().setLayout(new java.awt.FlowLayout());
        getContentPane().add(imgLabel);

        strCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strComboActionPerformed(evt);
            }
        });
        getContentPane().add(strCombo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strComboActionPerformed
        // TODO add your handling code here:
        JComboBox<String> cb = (JComboBox<String>)evt.getSource();
        int index = cb.getSelectedIndex();// 콤보박스 선택된 배열번호
        imgLabel.setIcon(images[index]);// 이미지레이블 컴포넌트
    }//GEN-LAST:event_strComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboActionEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboActionEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboActionEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboActionEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboActionEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLabel;
    private javax.swing.JComboBox<String> strCombo;
    // End of variables declaration//GEN-END:variables
}
