/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author kim
 */
public class ContainerComponentEx extends javax.swing.JFrame {

    /**
     * Creates new form ContainerComponentEx
     */
    public ContainerComponentEx() {
        initComponents();
        
        Panel1 p1 = new Panel1();
        p1.setSize(150, 150);
        p1.setLocation(10, 10);
        add(p1);
        
        Panel2 p2 = new Panel2();
        p2.setSize(150, 150);
        p2.setLocation(170, 10);
        add(p2);
        
        JButton btn = new JButton("OK");
        btn.setLocation(170, 10);
        btn.setSize(70, 30);
        add(btn);
        
        
        
    }

    
    // Panel1
    private class Panel1 extends JPanel {

        public Panel1() {
            setBackground(Color.yellow);
            add(new JLabel("Type ID"));
            add(new JTextField(10));
            add(new JLabel("Type Password"));
            add(new JTextField(10));
        }// Panel1()
        
    }// class Panel1()
    
    // Panel2
    private class Panel2 extends JPanel {

        public Panel2() {
            setBackground(Color.GREEN);
            add(new JLabel("Please Check!!"));
            add(new JCheckBox("C# JCheckBox"));
            add(new JCheckBox("C++ JCheckBox"));
        }// Panel2()
        
    }// class Panel2
    
 


    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Container & Component");
        setBackground(new java.awt.Color(0, 204, 102));
        setPreferredSize(new java.awt.Dimension(350, 250));
        setSize(new java.awt.Dimension(350, 250));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContainerComponentEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContainerComponentEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContainerComponentEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContainerComponentEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContainerComponentEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
