/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;



//import javax.swing.JFrame;
import javax.swing.JLabel;
/**
 *
 * @author kim
 */
public class KeyListenerEx extends javax.swing.JFrame {

    private  JLabel keyMessage[];
    /**
     * Creates new form KeyListenerEx
     */
    public KeyListenerEx() {
        initComponents();
        
        Container c = getContentPane();
        c.addKeyListener(new MyKeyListener());
        
        keyMessage = new JLabel[3];
        keyMessage[0]= new JLabel(" getKeyCode() ");
        keyMessage[1]= new JLabel(" getKeyChar() ");
        keyMessage[2]= new JLabel(" getKeyText() ");
        
        for(int i=0; i<keyMessage.length; i++)
        {
            c.add(keyMessage[i]);
            keyMessage[i].setOpaque(true);
            keyMessage[i].setBackground(Color.YELLOW);
        }// for
        
        c.setFocusable(true);
        c.requestFocus();        
        
    }// KeyListenerEx()
    
    
    class MyKeyListener extends KeyAdapter
    {
        public void keyPressed(KeyEvent e)
        {
            int keyCode = e.getKeyCode();
            char keyChar = e.getKeyChar();
            keyMessage[0].setText(Integer.toString(keyCode));
            keyMessage[1].setText(Integer.toString(keyChar));
            keyMessage[2].setText(KeyEvent.getKeyText(keyCode));
            System.out.println("KeyPressed");
        }// keyPressed()
        public void keyRealeased(KeyEvent e)
        {
            System.out.println("KeyRealeased");
        }
        public void keyTyped(KeyEvent e)
        {
            System.out.println("KeyTyped");
        }
    }// class MyKeyListener
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KeyListener ¿¹Á¦");
        setMinimumSize(new java.awt.Dimension(300, 150));
        setSize(new java.awt.Dimension(300, 150));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyListenerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyListenerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyListenerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyListenerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyListenerEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
