/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package _Beans;

import java.awt.Container;
import java.awt.event.*;
import javax.swing.JLabel;

/**
 *
 * @author kim
 */
public class MouseListenerAllEx extends javax.swing.JFrame {

    private JLabel la = new JLabel("No Mouse Event");
    
    /** Creates new form MouseListenerAllEx */
    public MouseListenerAllEx() {
        initComponents();
        
        Container c = getContentPane();
        
        // 府胶呈 按眉 积己
        MyMouseListener listener = new MyMouseListener();
        
        c.addMouseListener(listener);
        c.addMouseMotionListener(listener);
        c.add(la);
        la.setSize(200,200);
        la.setLocation(0, 0);
        setSize(300, 200);
        setVisible(true);
        
        
    }// MouseListenerAllEx()

    // 
    class MyMouseListener implements MouseListener, MouseMotionListener
    {

        @Override
        public void mouseClicked(MouseEvent e) {
            la.setText("mouseClicked" + e.getX() + "," + e.getY() + ")");
        }

        @Override
        public void mouseDragged(MouseEvent e) {
            la.setText("mouseDragged" + e.getX() + "," + e.getY() + ")");
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            la.setText("mouseEntered" + e.getX() + "," + e.getY() + ")");
        }

        @Override
        public void mouseMoved(MouseEvent e) {
            la.setText("mouseMoved" + e.getX() + "," + e.getY() + ")");
        }

        @Override
        public void mouseExited(MouseEvent e) {
            la.setText("mouseExited" + e.getX() + "," + e.getY() + ")");
        }

        @Override
        public void mousePressed(MouseEvent e) {
            la.setText("mousePressed" + e.getX() + "," + e.getY() + ")");
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            la.setText("mouseReleased" + e.getX() + "," + e.getY() + ")");
        }
        
    }// class MyMouseListener
    
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MouseListener客 MouseMotionListener 抗力");
        setMinimumSize(new java.awt.Dimension(300, 200));
        setSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseListenerAllEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseListenerAllEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseListenerAllEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseListenerAllEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseListenerAllEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
