/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author kim
 */
public class RadioButtonEx extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonEx
     */
    public RadioButtonEx() {
        initComponents();
        
        ButtonGroup g = new ButtonGroup();
        g.add(apple);
        g.add(pear);
        g.add(cherry);
        
        
        
    }

    
	
	
	// 이미지 싸이즈 재설정
	public ImageIcon imageSetSize(String url, int psize) {
//		ImageIcon cherryIcon = new ImageIcon("images/cherry.jpg");
		ImageIcon icon = new ImageIcon(url);
		java.awt.Image img = icon.getImage();
		java.awt.Image reImg = img.getScaledInstance(img.getWidth(null)/psize,img.getHeight(null)/psize, java.awt.Image.SCALE_SMOOTH);
		return new ImageIcon(reImg);
	}
	
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apple = new javax.swing.JRadioButton();
        pear = new javax.swing.JRadioButton();
        cherry = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("라디오버튼 만들기 예제");
        setMinimumSize(new java.awt.Dimension(250, 150));
        setPreferredSize(new java.awt.Dimension(250, 150));
        setSize(new java.awt.Dimension(250, 150));
        getContentPane().setLayout(new java.awt.FlowLayout());

        apple.setText("사과");
        getContentPane().add(apple);

        pear.setSelected(true);
        pear.setText("배");
        getContentPane().add(pear);

        cherry.setText("체리");
        cherry.setBorderPainted(true);
        cherry.setIcon(imageSetSize("images/cherry.jpg",4));
        cherry.setSelectedIcon(imageSetSize("images/selectedCherry.jpg",4));
        getContentPane().add(cherry);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton apple;
    private javax.swing.JRadioButton cherry;
    private javax.swing.JRadioButton pear;
    // End of variables declaration//GEN-END:variables
}
