/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

/**
 *
 * @author kim
 */
public class RadioButtonItemEventEx extends javax.swing.JFrame {

    private JRadioButton radio[] = new JRadioButton[3];
    private String text[] = {"사과", "배", "체리"};
    private ImageIcon image[] = {
      new ImageIcon("images/apple1.jpg")  ,
      new ImageIcon("images/pear1.jpg")  ,
      new ImageIcon("images/cherry1.jpg")
    };
    private JLabel imageLabel = new JLabel();
    
    /**
     * Creates new form RadioButtonItemEventEx
     */
    public RadioButtonItemEventEx() {
        initComponents();
        
        Container c = getContentPane();
        
        JPanel radioPanel = new JPanel();
        radioPanel.setBackground(Color.GRAY);
        
        ButtonGroup g = new ButtonGroup();
        for(int i=0; i<radio.length; i++){
            radio[i]= new JRadioButton(text[i]);
            g.add(radio[i]);
            radioPanel.add(radio[i]);
            radio[i].addItemListener(new MyItemListener());
        }// for
        
        radio[2].setSelected(true);
        c.add(radioPanel, BorderLayout.NORTH);
        c.add(imageLabel, BorderLayout.SOUTH);
        imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
        
        
    }// RadioButtonItemEventEx()

    
    
    class MyItemListener implements ItemListener
    {
        @Override
        public void itemStateChanged(ItemEvent e) {
            // 리스너에 변화가 있을때 itemEvent.DESELECTED 면 걍 나가고
            if(e.getStateChange() == ItemEvent.DESELECTED)
                return;
            
            // radio배열에 따라 선택되었다면 imageLabel에 image배열에 따라 설정
            if(radio[0].isSelected()) imageLabel.setIcon(image[0]);
            else if(radio[1].isSelected()) imageLabel.setIcon(image[1]);
            else imageLabel.setIcon(image[2]);
        }// itemStateChanged()
    }// class MyItemListener
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("라디오버튼 Item Event 예제");
        setMinimumSize(new java.awt.Dimension(250, 200));
        setPreferredSize(new java.awt.Dimension(250, 200));
        setSize(new java.awt.Dimension(250, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonItemEventEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonItemEventEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
