/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author user
 */
public class SliderChangeEx extends javax.swing.JFrame {

    private JLabel colorLabel;
    private JSlider sl[]=new JSlider[3];
    
    
    
    /**
     * Creates new form SliderChangeEx
     */
    public SliderChangeEx() {
        initComponents();
        
        
        Container c = getContentPane();
        
        // JSlider 초기화
        for(int i=0; i<sl.length; i++){
            sl[i] = new JSlider(JSlider.HORIZONTAL, 0, 255, 127);
            sl[i].setPaintLabels(true);
            sl[i].setPaintTicks(true);
            sl[i].setPaintTrack(true);
            sl[i].setMajorTickSpacing(50);
            sl[i].setMinorTickSpacing(i);
            
            sl[i].addChangeListener(new MyChangeListener());
            c.add(sl[i]);
        }// for
        
        
        // JSlider 배경색
        sl[0].setBackground(Color.RED);
        sl[1].setBackground(Color.GREEN);
        sl[2].setBackground(Color.BLUE);
        
        
        // 슬라이더 바 측정한 수 구하기
        int r = sl[0].getValue();
        int g = sl[1].getValue();
        int b = sl[2].getValue();
        
        
        colorLabel = new JLabel("   SLIDER EXAMPLE   ");
        // colorLabel 투명화, 배경색 설정
        colorLabel.setOpaque(true);
        colorLabel.setBackground(new Color(r,g,b));
        c.add(colorLabel);
        
        setSize(300, 230);
        setVisible(true);
        
    }// SliderChangeEx()

    
    
    class MyChangeListener implements ChangeListener {

        @Override
        public void stateChanged(ChangeEvent e) {
            int r = sl[0].getValue();
            int g = sl[1].getValue();
            int b = sl[2].getValue();
            
            colorLabel.setBackground(new Color(r,g,b));
        }// stateChanged()
        
    }// clas MyChangeListener
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("슬라이더와 ChangeEvent예제");
        setMinimumSize(new java.awt.Dimension(300, 230));
        setPreferredSize(new java.awt.Dimension(300, 230));
        setSize(new java.awt.Dimension(300, 230));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SliderChangeEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SliderChangeEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SliderChangeEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SliderChangeEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SliderChangeEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
