/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans._13;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JLabel;




class FlickeringLabel extends JLabel implements Runnable
{

    private long delay;
    
    public FlickeringLabel(String text, long delay) {
        super(text);// 상속확장부모(JLabel) 전달
        this.delay=delay;// 클래스내 공유할 밀리초 변수
        setOpaque(true);// 버튼 배경색 가능하도록 설정
        
        Thread th = new Thread(this);// Runnable에 상속한 Thread에 버튼객체 전달후 시작
        th.start();
    }// FlickerigLabel()

    @Override
    public void run() {
        int n=0;
        while(true)
        {
            if(n==0) setBackground(Color.YELLOW);
            else setBackground(Color.GREEN);
            if(n==0) n=1;
            else n=0;
            try {
                Thread.sleep(delay);
            } catch (InterruptedException e) {
                return ;
            } // try
        }// while
    }// run()
    
}// class FlickeringLabel








/**
 *
 * @author kim
 */
public class FlickeringLabelEx extends javax.swing.JFrame {

    /**
     * Creates new form FlickeringLabelEx
     */
    public FlickeringLabelEx() {
        initComponents();
        
        Container c = getContentPane();
        
        FlickeringLabel fLabel = new FlickeringLabel("깜박", 500);
        JLabel label = new JLabel("안깜박");
        FlickeringLabel fLabel2 = new FlickeringLabel("깜박", 500);
        
        c.add(fLabel);
        c.add(label);
        c.add(fLabel2);
        
        setVisible(true);
        
        
    }// FlickeringLabelEx()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlickeringLabelEx 예제");
        setMinimumSize(new java.awt.Dimension(300, 150));
        setPreferredSize(new java.awt.Dimension(300, 150));
        setSize(new java.awt.Dimension(300, 150));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlickeringLabelEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlickeringLabelEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlickeringLabelEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlickeringLabelEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlickeringLabelEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
