/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans._13;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JLabel;


class MyLabel1 extends JLabel {
    private int barSize=0;
    private int maxBarSize=0;

    public MyLabel1(int maxBarSize) {
        this.maxBarSize = maxBarSize;
    }// MyLabel()

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.MAGENTA);
        int width = (int) ((double) this.getWidth()/maxBarSize*barSize);
    }// paintComponent()
    
    synchronized public void fill(){
        if(barSize==maxBarSize){
            try{
                wait();
            } catch(InterruptedException e) {
                return;
            }// try
        }// if
        barSize++;
        repaint();
        notify();
    }// synchronized fill()
    
    synchronized public void consume(){
        if(barSize == 0){
            try{
                wait();
            } catch(InterruptedException e){
                return;
            }// try
        }// if
        barSize--;
        repaint();
        notify();
    }// synchronized consume()
    
}// class MyLabel



class ConsumerThread1 extends Thread {
    private MyLabel1 bar;

    public ConsumerThread1(MyLabel1 bar) {
        this.bar = bar;
    }// ConsumerThread()

    @Override
    public void run() {
//        super.run();
        while(true){
            try {
                sleep(200);
                bar.consume();
            } catch (InterruptedException e) {
                return;
            }
        }// while
    }// run()
    
}// class Consumer


/**
 *
 * @author kim
 */
public class TabAndThreadEx extends javax.swing.JFrame {

    private MyLabel1 bar = new MyLabel1(100);
    
    /**
     * Creates new form TabAndThreadEx
     */
    public TabAndThreadEx() {
        initComponents();
        
        bar.setBackground(Color.YELLOW);
        bar.setOpaque(true);
        bar.setLocation(20, 50);
        bar.setSize(300, 20);
        c.add(bar);
        c.setFocusable(true);
        c.requestFocus();
        
        ConsumerThread th = new ConsumerThread(bar);
        th.start();
        
    }// TabAndThreadEx()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("아무키나 빨리 눌러 바 채우기");
        setSize(new java.awt.Dimension(350, 250));

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cKeyPressed(evt);
            }
        });
        c.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyPressed
        bar.fill(); // 키를 누를 때마다 바가 1증가
    }//GEN-LAST:event_cKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabAndThreadEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabAndThreadEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabAndThreadEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabAndThreadEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabAndThreadEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel c;
    // End of variables declaration//GEN-END:variables
}
