/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans._13;

import java.awt.Container;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author kim
 */
public class ThreadTimerEx extends javax.swing.JFrame {

    class TimerThread extends Thread {
        
        private JLabel timerLabel;// 타이머레이블 객체 생성

        public TimerThread(JLabel timerLabel) {
            this.timerLabel = timerLabel;// 지정된 타이머 레이블 객체 저장
        }// TimerThread() 초기화

        @Override
        public void run() {
//            super.run();
            int n=0; // 카운터 초기화
            while(true){
               timerLabel.setText(Integer.toString(n)) ;
               n++;
               
                try {
                    Thread.sleep(1000);// Thread Process 1초 대기
                } catch (InterruptedException e) {
                    return ; // 예외가 발생하면 스레드 종료
                }// try
                       
            }// while
        }// run
        
    }// class TimerThread
    
    
    
    /**
     * Creates new form TimeThread
     */
    public ThreadTimerEx() {
        initComponents();
        
        Container c = getContentPane();// 컨테이너 값 얻어오기
        
        JLabel timerLabel = new JLabel();// 패널에 표시할 레이블 객체 생성
//        timerLabel.setFont(new Font(name, style, size));
        timerLabel.setFont(new Font("Gothic", Font.ITALIC, 80));
        c.add(timerLabel);
        
        // 타이머 쓰레드 생성
        TimerThread th = new TimerThread(timerLabel);
        th.start();// 타이머 쓰레드 실행
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thread를 상속받은 타이머 스레드 예제");
        setMinimumSize(new java.awt.Dimension(300, 170));
        setPreferredSize(new java.awt.Dimension(300, 170));
        setSize(new java.awt.Dimension(300, 170));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadTimerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadTimerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadTimerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadTimerEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadTimerEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
