/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans._13;

import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JLabel;

class TimerRunnable1 implements Runnable
{
    private JLabel timerLabel;

    public TimerRunnable1(JLabel timerLabel) {
        this.timerLabel = timerLabel;
    }// TimerRunnable()

    @Override
    public void run() {
        int n = 0;
        while(true){
            // n 타이머값을 레이블에 넣는다.
            timerLabel.setText(Integer.toString(n));
            n++;
            try {
                Thread.sleep(1000);// 1초 대기
            } catch (InterruptedException e) {
                return ;// 예외발생 쓰레드 종료
            }// try
        }// while
    }// run()
    
}// class TimerRunnable




/**
 *
 * @author kim
 */
public class ThreadInterruptEx extends javax.swing.JFrame {

    private Thread th;      // 쓰레드 선언
    private boolean btnOn;  // 버튼 활성화 체크
    /**
     * Creates new form ThreadInterruptEx
     */
    public ThreadInterruptEx() {
        initComponents();
        
        // TimerRunnable1(timerLabel)의 객체 runnable
        TimerRunnable1 runnable = new TimerRunnable1(timerLabel);
        th = new Thread(runnable);// 쓰레드 선언
        th.start();// 쓰레드 동작

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timerLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thread InterruptEx 예제");
        setMinimumSize(new java.awt.Dimension(300, 170));
        setPreferredSize(new java.awt.Dimension(300, 170));
        setSize(new java.awt.Dimension(300, 170));
        getContentPane().setLayout(new java.awt.FlowLayout());

        timerLabel.setFont(new java.awt.Font("Georgia", 2, 80)); // NOI18N
        getContentPane().add(timerLabel);

        jButton1.setText("kill Timer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // https://ict-nroo.tistory.com/22
        // https://ict-nroo.tistory.com/41?category=646168
        // 쓰레드 종료
        th.interrupt();// ThreadInterruptEx 선언된 th쓰레드 interrupt 메세지 발생후 
      
        JButton btn = (JButton) evt.getSource();// 이벤트 evt의 getSource를 JButton 객체로 얻어온다.

        // 코드 재작성
        // th.interrupt() 종료되므로 일시정지하여 재실행시키는 코드로 변경처리하고
        // 하단의 코드를 재수정
        if(btn.getActionCommand().equals("disable")) {
            btn.setActionCommand("enable");
            btn.setEnabled(true);
//            th.suspend();// 재실행
        } else  {// JButton을 비활성화 시킨다.
            btn.setActionCommand("disable");
            btn.setEnabled(false);  
//            th.resume();// 일시 정지
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadInterruptEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadInterruptEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadInterruptEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadInterruptEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadInterruptEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
