/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _Beans._13;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;


class RandomThread extends Thread {
    
    private Container contentPane;  // 컨텐트팬 선언
    private boolean flag=false;     // 쓰레드 선언
    public void finish(){           // 쓰레드 종료
        flag=true;
    }
    public RandomThread(Container contentPane) {
        this.contentPane = contentPane;
    }

    @Override
    public void run() {
//        super.run();

        while(true){
            // 위치값 선언
            int x = (int)(Math.random()*contentPane.getWidth());
            int y = (int)(Math.random()*contentPane.getHeight());
            
            // 반복 레이블 선언
            JLabel label = new JLabel("java");
            label.setSize(80,30);
            label.setLocation(x, y);
            contentPane.add(label);
            contentPane.repaint();
            try {
               Thread.sleep(300);   // 쓰레드 대기
               if(flag==true){
                   contentPane.removeAll();
                   label = new JLabel("finish");
                   label.setSize(80,30);
//                   label.setLocation(x, y);
                   label.setLocation(contentPane.getWidth()/2,contentPane.getHeight()/2);
                   label.setForeground(Color.RED);
                   contentPane.add(label);
                   contentPane.repaint();
                   return ;         // 쓰레드 종료
               }
            } catch(InterruptedException e){
                return ;            // 쓰레드 종료
            }
        }// while
        
    }// run()
    
}// class RandomThread






/**
 *
 * @author kim
 */
public class ThreadFinishFlagEx extends javax.swing.JFrame {

    // 쓰레드 레퍼런스
    private RandomThread th;
    
    /**
     * Creates new form ThreadFinishFlagEx
     */
    public ThreadFinishFlagEx() {
        initComponents();
        
        Container c = getContentPane();
        c.setLayout(null);
        
        c.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
//                super.mousePressed(e);
                th.finish();
            }// mousePressed()
        });// MouseListenr()
        
        setVisible(true);
        th = new RandomThread(c);
        th.start();
    }// ThreadFinishFlagEx()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ThreadFinishFlagEx 예제");
        setSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadFinishFlagEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadFinishFlagEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadFinishFlagEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadFinishFlagEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadFinishFlagEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
